services:
  timescaledb:
    image: timescale/timescaledb:latest-pg15
    container_name: aerotrace-timescaledb

    environment:
      POSTGRES_USER: ${AEROTRACE_DB_USERNAME}
      POSTGRES_PASSWORD: ${AEROTRACE_DB_PASSWORD}
      POSTGRES_DB: ${AEROTRACE_DB_NAME}

    ports:
      - "5432:5432"

    volumes:
      - aerotrace-db-data:/var/lib/postgresql/data

    networks:
      - aerotrace-network

    healthcheck:
      test:
        - CMD-SHELL
        - >
          pg_isready
          -U "${AEROTRACE_DB_USERNAME}"
          -d "${AEROTRACE_DB_NAME}"
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s

    restart: unless-stopped

  otel-storage-init:
    image: alpine:3.22
    container_name: aerotrace-otel-storage-init
    command:
      - sh
      - -c
      - >
        mkdir -p
        /var/lib/otelcol/storage
        /var/lib/otelcol/compaction
        &&
        chown -R 10001:10001
        /var/lib/otelcol
    volumes:
      - aerotrace-otelcol-data:/var/lib/otelcol
    restart: "no"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.157.0
    container_name: aerotrace-otel-collector
    env_file:
      - ./otel-collector.env
    command:
      - --config=/etc/otel-collector-config.yaml
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml:ro
      - aerotrace-otelcol-data:/var/lib/otelcol
    ports:
      - "4317:4317"
      - "4318:4318"
      - "127.0.0.1:8888:8888"
    depends_on:
      timescaledb:
        condition: service_healthy
      otel-storage-init:
        condition: service_completed_successfully
    networks:
      - aerotrace-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U \"$${POSTGRES_USER}\" -d \"$${POSTGRES_DB}\"" ]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 10s
    restart: unless-stopped

  backend:
    profiles:
      - app

    build:
      context: ./backend
      dockerfile: Dockerfile

    image: aerotrace-backend:local
    container_name: aerotrace-backend

    environment:
      AEROTRACE_DB_URL: >-
        jdbc:postgresql://timescaledb:5432/${AEROTRACE_DB_NAME}
      AEROTRACE_DB_USERNAME: ${AEROTRACE_DB_USERNAME}
      AEROTRACE_DB_PASSWORD: ${AEROTRACE_DB_PASSWORD}

    ports:
      - "8080:8080"

    depends_on:
      timescaledb:
        condition: service_healthy

    healthcheck:
      test:
        - CMD
        - curl
        - --fail
        - --silent
        - --show-error
        - http://localhost:8080/actuator/health
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 20s

    networks:
      - aerotrace-network

    restart: unless-stopped

volumes:
  aerotrace-db-data:

  aerotrace-otelcol-data:
    name: aerotrace-otelcol-data

networks:
  aerotrace-network:
    driver: bridge