receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  otlp_http/aerotrace:
    endpoint: "${env:AEROTRACE_BACKEND_ENDPOINT}"

    encoding: json
    compression: none
    timeout: 5s

    headers:
      Authorization: "Bearer ${env:AEROTRACE_API_KEY}"

    retry_on_failure:
      enabled: true
      initial_interval: 1s
      max_interval: 10s
      max_elapsed_time: 0s

    sending_queue:
      enabled: true
      num_consumers: 2
      sizer: items
      queue_size: 50000
      block_on_overflow: false
      storage: file_storage/aerotrace

service:
  extensions:
    - file_storage/aerotrace

  telemetry:
    metrics:
      level: normal

      readers:
        - pull:
            exporter:
              prometheus:
                host: 0.0.0.0
                port: 8888
                without_type_suffix: true
                without_units: true

  pipelines:
    traces:
      receivers:
        - otlp
      processors:
        - batch
      exporters:
        - otlp_http/aerotrace

extensions:
  file_storage/aerotrace:
    directory: /var/lib/otelcol/storage
    create_directory: true
    directory_permissions: "0750"
    timeout: 1s
    max_size: 536870912
    fsync: true
    compaction:
      on_start: true
      cleanup_on_start: true
      directory: /var/lib/otelcol/compaction