spring:
  application:
    name: aerotrace-backend

  threads:
    virtual:
      enabled: true

  main:
    keep-alive: true

  datasource:
    url: ${AEROTRACE_DB_URL:jdbc:postgresql://localhost:5432/aerotrace}
    username: ${AEROTRACE_DB_USERNAME:postgres}
    password: ${AEROTRACE_DB_PASSWORD:postgres}

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: false
    validate-on-migrate: true
    clean-disabled: true

server:
  port: 8080

management:
  endpoint:
    health:
      show-details: never

aerotrace:
  ingest:
    max-spans-per-request: 5000
    max-request-body-bytes: 10485760
    jdbc:
      batch-size: 1000